name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean environment
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build the project
        run: npm run build

      - name: Export the project
        run: npm run export

      - name: Verify out directory
        run: |
          if [ ! -d "out" ]; then
            echo "Error: out directory does not exist."
            exit 1
          fi

      - name: Remove existing gh-pages directory
        run: rm -rf gh-pages

      - name: Clone GitHub Pages repository
        run: git clone --branch=main https://github.com/IshuSinghSE/IshuSinghSE.github.io.git gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Copy built files
        run: cp -r out/* gh-pages/

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global credential.helper 'store --file=.git/credentials'
          echo "https://${{ secrets.GH_TOKEN }}:@github.com" > .git/credentials
          git add .
          git commit -m 'Deploy Next.js app'
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}